### ISSUE TITLE
wifi toggle feature request

### ISSUE THREAD

**Issue by 532910** [mozilla/ichnaea#643] opened 2018-12-30 15:29 UTC
Could you make the app to switch wifi on on new session start.

**Comment by jwhitlock** [comment] 2019-10-14 14:30
This appears to be a duplicate of https://github.com/mozilla/MozStumbler/issues/1842, which is the right place to file it.

**Closed as completed by jwhitlock** 2019-10-14 14:30 UTC

**Comment by 532910** [comment] 2019-10-14 14:35
My fault, sorry!
