### ISSUE TITLE
Allow downloading specific regions

### ISSUE THREAD

**Issue by jidanni** [mozilla/ichnaea#498] opened 2017-03-04 01:02 UTC
https://location.services.mozilla.com/downloads only has worldwide downloads.
The user might only be interested in download data for a specific region or bounding box.
It would be a waste for him to download the remaining 99.9% which he doesn't need.

**Comment by jidanni** [comment] 2017-03-04 01:25
See for example http://wiki.opencellid.org/wiki/API ,
But note http://wiki.opencellid.org/ says that site may be closing.

**Comment by hannosch** [comment] 2017-03-06 13:55
I thinks this is a duplicate of #488.

**Closed by hannosch** 2017-03-06 13:55 UTC
