### ISSUE TITLE
Translation for location.services.mozilla.com

### ISSUE THREAD

**Issue by Djfe** [mozilla/ichnaea#516] opened 2018-03-25 06:14 UTC
In-case the frontend receives an update to the new Mozilla design in the future, it would be nice if the strings could also be saved to ftl files, so that the frontend can be localized by contributors at https://pontoon.mozilla.org/

**Comment by jwhitlock** [comment] 2020-09-11 19:55
There is a newer issue, (#1253) asking for localization to Russian. Usually, I'd mark the newer bug as a duplicate of the older one, but in this case, there has been more discussion on the newer bug, and it shows that there is still some interest.

**Closed by jwhitlock** 2020-09-11 19:55 UTC
