### ISSUE TITLE
StaleDataError: UPDATE statement on table 'wifi_shard_N' expected to update X rows; Y were matched

### ISSUE THREAD

**Issue by willkg** [mozilla/ichnaea#990] opened 2019-11-05 19:13 UTC
We're testing a new infrastructure, 4 years of changes, and an Python 2 -> 3 migration all on stage right now. One of the things we did was add a geosubmit export to prod which points to stage, so stage has a steady stream of incoming reports to process.

One of the errors we're hitting is this:

```
StaleDataError: UPDATE statement on table 'wifi_shard_8' expected to update 457 row(s); 423 were matched.
  File "ichnaea/taskapp/task.py", line 79, in __call__
    result = super(BaseTask, self).__call__(*args, **kw)
  File "celery/app/trace.py", line 648, in __protected_call__
    return self.run(*args, **kwargs)
  File "ichnaea/data/tasks.py", line 145, in update_wifi
    station.WifiUpdater(self, shard_id=shard_id)()
  File "ichnaea/data/station.py", line 566, in __call__
    session, shard, shard_values, stats_counter
  File "ichnaea/data/station.py", line 530, in update_shard
    session.bulk_update_mappings(shard, updates)
  File "sqlalchemy/orm/session.py", line 2860, in bulk_update_mappings
    mapper, mappings, True, False, False, False, False
  File "sqlalchemy/orm/session.py", line 2899, in _bulk_save_mappings
    transaction.rollback(_capture_exception=True)
  File "sqlalchemy/util/langhelpers.py", line 68, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "sqlalchemy/util/compat.py", line 153, in reraise
    raise value
  File "sqlalchemy/orm/session.py", line 2884, in _bulk_save_mappings
    update_changed_only,
  File "sqlalchemy/orm/persistence.py", line 180, in _bulk_update
    bookkeeping=False,
  File "sqlalchemy/orm/persistence.py", line 1029, in _emit_update_statements
    % (table.description, len(records), rows)
```

https://sentry.prod.mozaws.net/operations/location-stage/issues/6582655/

The code in question is here:

https://github.com/mozilla/ichnaea/blob/4b7aa181ddd708c3f0ab9fa6031c49a707d07d69/ichnaea/data/station.py#L530

We're not seeing these errors in prod. Maybe this is caused by different code, dependencies, or data context between stage and prod?

This issue covers looking into this.

**Comment by hannosch** [comment] 2019-11-05 19:42
I’m not sure, but this may only occur with a fairly empty database at first and concurrent tasks all trying to update the same rows.

One thing you could try is to raise the Mysql isolation level from repeatable read to serializable (indb.py). This should turn all select statements into “for share” statements, so all selected rows are locked and other transactions cannot update or delete them.

**Comment by jwhitlock** [comment] 2019-11-05 19:52
This sounds similar to the issue fixed with PR #943. ``bulk_update_mappings`` fails when an update doesn't change existing data. My solution was to go back to using the ORM, which keeps track of when a field is updated.

**Comment by willkg** [comment] 2019-11-05 19:56
I was thinking along these lines, too--that this is primarily because the database is empty-ish.

One of the things I've been looking at over the last 30 minutes is the context. We're seeing like 25 of these an hour in the `update_wifi` task. When it happens, the `update_wifi` task is retried 180s later. 

Looks like the `update_wifi` task executes like 4k times an hour. So of those 4k times it executes, 25 fail with the `StaleDataError`.

One thing I don't know offhand is when a `update_wifi` celery task fails with this error, does it try to update those stations (I think it's trying to update stations, but I can't tell) again or does the celery task retry, but the data that it failed on is lost forever?

**Comment by hannosch** [comment] 2019-11-05 20:57
The station updater has custom retry logic in its call method. It dequeues the data (which is really just a pop from a redis list) than in a for loop tries to do its work, on a retry-able error it tries up to 3 times, after which the task is done and the data is either used successfully or lost. What is considered retry-able is set as a class attribute tuple.

The codebase in general assumes that no incoming data has to be preserved. Data is only valuable if it gets confirmed multiple times over longer periods of times, so loosing some of it is always ok.

**Comment by willkg** [comment] 2019-11-06 18:21
We talked about this on the weekly call and I think all observations and evidence suggests this could happen in prod, but doesn't because the data is more stable. Given that, it behooves us to defer this until after we've got prod updated to the new infrastructure.

**Comment by jwhitlock** [comment] 2019-11-20 20:32
I looked into this some more, and I don't think it has the same cause as PR #943. For that PR, the `cell_area` table was being updated in a way that didn't change the contents for some rows, so it could be addressed by using the ORM to avoid sending needless "no update" updates.

I started by looking at the most common error, station updates that used the `change` or `replace` transition, but I wasn't able to find a code path where there was no change to the row. For `change`, the `samples` count would always increase by one or more, and for `replace`, the `source` would switch from `query` to `gnss` (or the integer equivalent). So, there doesn't appear to be a bug in the code that would cause a 'no update' UPDATE to be executed.

The code that fails to execute `confirm` transitions appears to be better for debugging:

https://sentry.prod.mozaws.net/share/issue/75dc5aea37ce4e08869fb6d4c30067df/

A recent event expects to update two rows, and just updates one. The data sent, which just updates the `last_seen` column, is:

```python
[
  {'last_seen': datetime.date(2019, 11, 20), 'mac': 'e4186bd69b11'},
  {'last_seen': datetime.date(2019, 11, 20), 'mac': '0c8063acee84'}
]
```

The SQLAlchemy engine logs would show something like:

```
UPDATE wifi_shard_6 SET last_seen=%(last_seen)s WHERE wifi_shard_6.mac = %(wifi_shard_6_mac)s
({'last_seen': datetime.date(2019, 11, 20), 'wifi_shard_6_mac': b'\xe4\x18k\xd6\x9b\x11'}, 
 {'last_seen': datetime.date(2019, 11, 20), 'wifi_shard_6_mac': b'\x0c\x80c\xac\xee\x84'})
```

Looking at the stage database, there are entries for both keys, and the `last_seen` column would be updated:

```
select hex(mac), last_seen from wifi_shard_6 where mac in (unhex('e4186bd69b11'), unhex('0c8063acee84'));
+--------------+------------+
| hex(mac)     | last_seen  |
+--------------+------------+
| 0C8063ACEE84 | 2019-11-12 |
| E4186BD69B11 | 2019-11-12 |
+--------------+------------+
2 rows in set (0.00 sec)
```

I can't think why this update failed to find and update both rows. This doesn't feel like a race condition, but I'm not familiar with the details of MySQL transactions. Is it possible to lock a single row, and cause a multi-row `UPDATE` to fail?

A recent issue https://github.com/sqlalchemy/sqlalchemy/issues/4831, closed for lack of activity, seemed to have similar issues. We're using PyMySQL as suggested, not mysqlconnector. We may be able to implement `handle_error()` to get more information. Or, we could re-write to avoid `bulk_update_mappings`.

**Comment by jwhitlock** [comment] 2019-12-03 21:04
Now that the new stack is in production, this is happening a lot more there as well.

I wondered if the issue was a corrupt index. On a whim, I tried running `OPTIMIZE TABLE` in stage. It was successful, but resulted in the station updating tasks running more slowly. It appears the database is the limiting factor on task speed, and rebuilding the indexes resulted in more database contention. This may be because writing new rows to a rebuilt index is slower, or because the `SELECT`s were faster, and more tasks got to competing writes at once.

It did not make the `StaleDataError`s or the deadlocks from #991 go away. The `StaleDateError`s jumped 10x for the hour after the `OPTIMIZE`, and deadlocks jumped about 4x, Both died down to the regular rate after 2 hours.

I suspect that similar actions will fix this and the deadlocks in #991, and it is slightly easier to get info on deadlocks, so I'm going to focus on those.

**Comment by hannosch** [comment] 2019-12-08 10:50
One other thought: You might be limited by a lack of RAM on the db instance. The indices should all fit into RAM and did at some point. But with the data growth over the last years, this might no longer be true.

Once you rebuild the index, the data is all flushed from memory to disk and it takes a while for the hot data of that table to get back into contested RAM.

IIRC we used a larger database instance type every two years or so and adjusted db size and persistent iops values at those times. But it might be a while since that happened an the db size has probably at least doubled since.

So maybe for the moment throwing more hardware at the problem might actually help :-)

**Comment by jwhitlock** [comment] 2020-01-08 16:55
The research for this issue is mostly in another bug, starting around https://github.com/mozilla/ichnaea/issues/991#issuecomment-561353577. To summarize, my best guess about what is going on is:

* Two celery tasks load a work unit where there is an overlap in rows that would be touched. For example, two work units could have observations for the same cell tower.
* Both tasks are able to read the current contents of the rows, and then prepare a bulk update to update existing records. For the competing cell tower updates, both would attempt to set the ``last_seen`` column to today and increment the ``sample`` column.
* MySQL uses row-level locking to ensure that only one task updates the desired rows. Sometimes this can result in a deadlock, but sometimes it just forces one task to update before the other. If there is a perfect overlap, then some updates are detected as null operations. For example, task 1 sets ``last_seen`` to today and increments ``sample`` from 3 to 4, and task 2 attempts to do the same. MySQL reports this as less rows being updated than update statements.
* SQLAlchemy expects the number of updated rows to match the number of updates, and panics by rolling back and raising a ``StaleDataError``.

Some reasons this may be worse than a few years ago:
* MySQL 5.6.?? → 5.7.26 changed the transaction code, in a way that tickled this issue
* Memory pressure means indexes are loaded from disk, making it take longer to acquire the locks and increasing the chances of overlaps. Using the calculations from https://dba.stackexchange.com/a/2194, we're below the memory needed for InnoDB to cache data and indexes in memory. We'd need a 3x increase for in-memory indexes, and a 6x increase for data and indexes. This is cost prohibitive.

The change to ``SELECT ... WITH UPDATE`` will move the lock acquisition to ``SELECT`` time rather than ``UPDATE`` time, but at the risk of locking more rows than are needed. In staging, this had the effect of eliminating ``StaleDataError``s for the station updating task, down from hundreds an hour. There was an increase in Lock Wait Timeout Exceeded errors, from 0 to 6 a day, after three retries with sleep.

I believe the next steps are:
* Add lock retry logic to cell area and datamap update tasks
* Roll out ``SELECT ... WITH UPDATE`` to cell area and datamap tasks
* Investigate metrics to detect stale station data, with a goal of reducing the working data set

**Comment by jwhitlock** [comment] 2020-01-09 15:01
We're also counting the database lock errors that are retried. After the change to ``SELECT ... WITH UDPATE``, the number of deadlocks (code 1213) increased, up to around 600 per hour at first, and settling to 50-100 per hour after a day. There was a spike of 30 lock timeouts (code 1205), but most hours there are none. It appears a sleep and retry is sufficient to deal with most deadlocks, with about 0.3% not resolving in 3 retries.

I'm going to roll out the retry logic against issue #991, then add the ``SELECT ... WITH UPDATE`` against this task.

**Comment by jwhitlock** [comment] 2020-01-17 16:57
The changes have been pushed to production and stage. The ``SELECT ... WITH UPDATE`` took care of ``StaleDataError``s in the cell area and data map updaters. There was a significant increase in deadlocks in the cell area updater, so I did further work to move the ``SELECT`` earlier in the process in PR #1058.

I think there is more to do with processing, but this issue is solved.

**Closed by jwhitlock** 2020-01-17 16:57 UTC
